
import { Inter } from 'next/font/google'

import './styles/globals.css'
import Nav from './components/nav';
import initFirebase from './firebase/firebase';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'runPen',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en" className="h-full">
      <head><title>runPen</title></head>
      <body className={inter.className}>
        
          <Nav/>
          {children}
        
      </body>
    </html>
  );
}
